services:
  - type: web
    name: coilws-n8n
    env: node
    plan: free
    buildCommand: |
      npm install --omit=dev
    startCommand: |
      bash -c "export N8N_SKIP_MIGRATIONS=true; exec node /opt/render/project/src/node_modules/n8n/bin/n8n start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: N8N_PORT
        value: 10000
      - key: N8N_SKIP_MIGRATIONS
        value: "true"
      - key: N8N_ENCRYPTION_KEY
        value: coilwsScraperKey121!
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "false"
      - key: N8N_LOG_LEVEL
        value: debug
      - key: GENERIC_TIMEZONE
        value: Asia/Kolkata
      - key: DB_TYPE
        value: mysqldb
      - key: DB_MYSQLDB_HOST
        value: 107.180.1.212
      - key: DB_MYSQLDB_PORT
        value: 3306
      - key: DB_MYSQLDB_DATABASE
        value: n8n_prod2
      - key: DB_MYSQLDB_USER
        value: n8n_user2
      - key: DB_MYSQLDB_PASSWORD
        sync: false
      - key: DB_MYSQLDB_SSL
        value: "false"
      - key: DB_MYSQLDB_CHARSET
        value: utf8mb4
      - key: DB_MYSQLDB_COLLATION
        value: utf8mb4_unicode_ci
      - key: WEBHOOK_TUNNEL_URL
        value: https://coilws-n8n.onrender.com
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        sync: false
      - key: N8N_BLOCK_ENV_ACCESS_IN_NODE
        value: "false"
      - key: N8N_GIT_NODE_DISABLE_BARE_REPOS
        value: "true"
      - key: N8N_RUNNERS_ENABLED
        value: "true"
      - key: DB_SQLITE_POOL_SIZE
        value: 2
      - key: TEST_MODE
        value: "false"
      - key: SCRAPE_ROOT_URL
        value: https://coilws.com
      - key: BOTPRESS_API_KEY
        sync: false
      - key: BOTPRESS_TOKEN
        sync: false
      - key: BOTPRESS_BOT_ID
        value: 371e3dbf-7622-4004-bb67-dbce197d1cde
      - key: BOTPRESS_WORKSPACE_ID
        value: wkspace_01K91NWX0NF4CDJFC86ZPERG1R
      - key: BOTPRESS_KB_ID
        value: kb-default
